INSERT INTO PET(ID, PET_NAME) VALUES (99, 'Antonio');
INSERT INTO PET(ID, PET_NAME) VALUES (100, 'Valerio');
INSERT INTO PET(ID, PET_NAME) VALUES (101, 'Egorio');
INSERT INTO PET(ID, PET_NAME) VALUES (102, 'Vladimio');
INSERT INTO PET(ID, PET_NAME) VALUES (103, 'Eugenio');